name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*  # Sube todos los archivos generados a la release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
